AutoForm.debug()
Meteor.subscribe 'users'
Meteor.subscribe 'relations'
Meteor.subscribe 'knots'
Meteor.subscribe 'badges'
Meteor.subscribe 'patches'

Template.main.helpers
  relations: ->
    Relations.find open: true

Template.profile.helpers
  email: ->
    Meteor.user().emails[0].address
  relations: ->
    Relations.find userIds: '$in': [ Meteor.userId() ]
  relationLink: ->
    '/relation/' + @_id
  badges: ->
    Badges.find userIds: '$in': [ Meteor.userId() ]
  pinnableKnots: ->
    Knots.find 'claim': $elemMatch: userId: Meteor.userId()
  possiblePatch: ->
    Patches.findOne _id: $in: _.chain(@claim).select((e) ->
      e.userId == Meteor.userId()
    ).map((e) ->
      e.patchId
    ).value()
Template.users.helpers
  users: ->
    Meteor.users.find()
  email: ->
    if @emails.length
      @emails[0].address
    else
      ''
Template.relations.helpers
  relations: ->
    Relations.find()
  relationLink: ->
    '/relation/' + @_id
  relationName: ->
    @displayName
  insertRelationFormSchema: ->
    Schemas.Relation

Template.relationPage.helpers
  relation: ->
    Relations.findOne _id: FlowRouter.getParam('_id')
  members: ->
    if @userIds
      Meteor.users.find _id: $in: @userIds
    else
      false
  email: ->
    @emails[0].address
  formId: ->
    'updateRelationForm-' + @_id
  knots: ->
    Knots.find relationId: @_id
  creatorName: ->
    Meteor.users.findOne(@createdBy).name()
  claimaintName: ->
    Meteor.users.findOne(@userId).name()
  patchName: ->
    Patches.findOne(@patchId).displayName
  preKnot: ->
    relationId: @_id
    createdBy: Meteor.userId()
    createdAt: new Date
  insertKnotFormSchema: ->
    new SimpleSchema(Schemas.Knot)
  canEdit: ->
    @createdBy == Meteor.userId()
  canView: ->
    true
  canPost: ->
    _.include(@userIds, Meteor.userId()) or @open

Template.patches.helpers
  patches: ->
    Patches.find()
  formId: ->
    'updatePatchForm-' + @_id
Template.badges.helpers
  badges: ->
    Badges.find()
  formId: ->
    'updateBadgeForm-' + @_id

# ---
# generated by js2coffee 2.2.0
